### ISSUE TITLE
Inconsistent UI on main web page for manual SOC

### ISSUE THREAD

**Issue by andlem74** [openWB/openwb-ui-settings#339]
Affected version: 2.1.0
After the user has set an initial SOC (e. g. 15%) on the main web page, the displayed SOC will increase as charging progresses, e. g. to 45%. At any time, the user can edit the SOC again. The pop-up will show the current value, e. g. 45%, and the user will be able to change it, e. g. to 48% which is what the car reports. Afterwards, the value the user entered will not be used to change the current value, but the initial one the user entered earlier, i. e. the initial SOC value of 15% will be replaced. Hence, the displayed value will change to 48%-15%+45%-15%=63%. This is unexpected and confusing. The user will expect the estimated SOC to be updated to the value of 48% because that’s what he entered.

**Comment by benderl** [comment]
This is not a fault of of the UI. Please open a similar issue in the core repository.
https://github.com/openWB/core
